name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Echo token
        run:
          echo Token is "${{ secrets.BLOGGER_PAT }}"
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v3.0.0
        with:
          reactions: true
          token: "TOKEN_VALUE"
          commands: |
            deploy
