name: Slash Command Dispatch
on:
  issue_comment:
    types: [ created ]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.BLOGGER_PAT }}
          reactions: "seen", "dispatched"
          allow-edits: true
          commands: |
            deploy
            integration-test
            build-docs
