name: docker-build-command
on:
  repository_dispatch:
    types: [ docker-build-command ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Clean Install
        run: mvn -B clean install --file blogger-be/pom.xml

      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v2
        with:
          name: jar-artifact
          path: ${{ github.workspace }}/blogger-be/target/*.jar
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Download build artefact
        uses: actions/download-artifact@v1
        with:
          name: jar-artifact
          path: target/

      - name: Docker build
        run: |
          docker build . -t kaze2/blogger-be:latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSKEY }}

      - name: Docker push
        run: |
          docker push kaze2/blogger-be:latest

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BLOGGER_PAT_V2 }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
