name: docker-build-command
on:
  repository_dispatch:
    types: [ docker-build-command ]
jobs:
  dockerBuildAndPush:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSKEY }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: kaze2/blogger-be:latest

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.BLOGGER_PAT_V2 }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
