name: docker-build-command
on:
  repository_dispatch:
    types: [ docker-build-command ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Repeat the message
        run: |
          message=${{ github.event.client_payload.slash_command.args.named.message }}
          echo "Message: $message"
